name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this branch
        uses: actions/checkout@master
      - name: Install node modules
        run: yarn --frozen-lockfile --check-files
      - name: Deploy the project
        run: |
          git config --global user.name 'github Actions'
          git config --global user.email 'goth-octo@users.noreply.github.com'
          yarn deploy
